<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="43822" started-at="2017-01-30T15:27:12Z" finished-at="2017-01-30T15:27:56Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="43822" started-at="2017-01-30T15:27:12Z" finished-at="2017-01-30T15:27:56Z">
      <class name="com.netflix.driver.TestDriver">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.netflix.driver.TestDriver@5702b3b1]" name="beforeTest" is-config="true" duration-ms="9" started-at="2017-01-30T10:27:12Z" finished-at="2017-01-30T10:27:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.netflix.driver.TestDriver@5702b3b1]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2017-01-30T10:27:12Z" finished-at="2017-01-30T10:27:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="run()[pri:0, instance:com.netflix.driver.TestDriver@5702b3b1]" name="run" duration-ms="43793" started-at="2017-01-30T10:27:12Z" finished-at="2017-01-30T10:27:56Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.netflix.driver.TestDriver.run(TestDriver.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- run -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.netflix.driver.TestDriver@5702b3b1]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-01-30T10:27:56Z" finished-at="2017-01-30T10:27:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.netflix.driver.TestDriver -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
